######################################################################
# Automatically generated by qmake (3.0) Di. Mai 27 13:28:24 2014
######################################################################

TEMPLATE = app
TARGET = FilterShop
INCLUDEPATH += ./src

# Input
HEADERS += src/ImageViewer.hpp src/Filter.hpp
SOURCES += src/ImageViewer.cpp src/main.cpp src/Filter.cpp
QT += printsupport
