#####################################################################
# Automatically generated by qmake (3.0) Mo. Juni 23 03:02:05 2014
######################################################################

TEMPLATE = app
TARGET = filtershop
INCLUDEPATH += . src

# Input
HEADERS += src/Filter.hpp src/ImageViewer.hpp src/MatHelper.hpp
SOURCES += src/Filter.cpp src/ImageViewer.cpp src/main.cpp src/MatHelper.cpp
LIBS += -lQt5Widgets
QT += printsupport
QMAKE_CXXFLAGS += -std=c++11
