######################################################################
# Automatically generated by qmake (3.0) Di. Mai 27 13:28:24 2014
######################################################################

TEMPLATE = app
TARGET = FilterShop
INCLUDEPATH += .

# Input
HEADERS += ImageViewer.hpp Filter.hpp
SOURCES += ImageViewer.cpp main.cpp Filter.cpp
QT += printsupport
